// Regenerates api/_data.ts from data/*.json. Run after editing data files:
//   node --experimental-strip-types scripts/gen-data-module.mts
// (api/_data.ts inlines the JSON because Vercel serves api/*.ts as standalone
// ESM modules where runtime JSON imports would need import attributes.)
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

const pj = JSON.parse(readFileSync('data/panchayats.json', 'utf8'));
const cj = JSON.parse(readFileSync('data/crops.json', 'utf8'));
const fbs: Record<string, unknown> = {};
for (const f of readdirSync('data/fallback').filter((f) => f.endsWith('.json')).sort()) {
  fbs[f.slice(0, -5)] = JSON.parse(readFileSync(`data/fallback/${f}`, 'utf8'));
}
const out = `// GENERATED by scripts/gen-data-module.mts - do not edit by hand.
import type { Panchayat, Advisory } from './_types.js';
import type { Crop } from './_rules.js';

export const panchayatsDoc = ${JSON.stringify(pj, null, 2)} as unknown as { source: string; panchayats: Panchayat[] };
export const panchayats: Panchayat[] = panchayatsDoc.panchayats;
export const crops = ${JSON.stringify(cj.crops, null, 2)} as unknown as Crop[];
export const fallbacks: Record<string, Advisory> = ${JSON.stringify(fbs, null, 2)} as unknown as Record<string, Advisory>;
`;
writeFileSync('api/_data.ts', out);
console.log('api/_data.ts regenerated:', Object.keys(fbs).length, 'fallbacks');
