// GENERATED by scripts/gen-data-module.mts - do not edit by hand.
// Vercel compiles each api/*.ts as a standalone ESM module; JSON imports
// need import attributes Node would reject here, so data is inlined as TS.
import type { Panchayat } from './_types.js';
import type { Crop } from './_rules.js';
import type { Advisory } from './_types.js';

export const panchayatsDoc = {
  "source": "Coordinates geocoded 2026-09-25 via Google Maps geocoder. Demo coverage set - the LG Directory scheme extends this to every panchayat in India (same id structure: state/district/name).",
  "panchayats": [
    {
      "id": "tn-thanjavur-papanasam",
      "name": "Papanasam",
      "name_ta": "பாபநாசம்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.9296,
      "lng": 79.2705
    },
    {
      "id": "tn-thanjavur-kumbakonam",
      "name": "Kumbakonam",
      "name_ta": "கும்பகோணம்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.9602,
      "lng": 79.3845
    },
    {
      "id": "tn-thanjavur-orathanadu",
      "name": "Orathanadu",
      "name_ta": "ஓரத்தநாடு",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.6277,
      "lng": 79.2525
    },
    {
      "id": "tn-thanjavur-thiruvaiyaru",
      "name": "Thiruvaiyaru",
      "name_ta": "திருவையாறு",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.8799,
      "lng": 79.106
    },
    {
      "id": "tn-thanjavur-melattur",
      "name": "Melattur",
      "name_ta": "மேலத்தூர்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.843,
      "lng": 79.262
    },
    {
      "id": "tn-thanjavur-ammapettai",
      "name": "Ammapettai",
      "name_ta": "அம்மாபேட்டை",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.7971,
      "lng": 79.3157
    },
    {
      "id": "tn-thanjavur-budalur",
      "name": "Budalur",
      "name_ta": "புதலூர்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.7968,
      "lng": 78.9769
    },
    {
      "id": "tn-thanjavur-vallam",
      "name": "Vallam",
      "name_ta": "வல்லம்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.714,
      "lng": 79.0702
    },
    {
      "id": "tn-thanjavur-thirukattupalli",
      "name": "Thirukattupalli",
      "name_ta": "திருக்காட்டுப்பள்ளி",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.849,
      "lng": 78.9542
    },
    {
      "id": "tn-thanjavur-sengipatti",
      "name": "Sengipatti",
      "name_ta": "செங்கிபட்டி",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.7108,
      "lng": 78.9797
    },
    {
      "id": "tn-thanjavur-ayyampettai",
      "name": "Ayyampettai",
      "name_ta": "ஐயம்பேட்டை",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.8963,
      "lng": 79.1944
    },
    {
      "id": "tn-thanjavur-thiruvonam",
      "name": "Thiruvonam",
      "name_ta": "திருவோணம்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.5077,
      "lng": 79.1591
    },
    {
      "id": "tn-thanjavur-pattukkottai",
      "name": "Pattukkottai",
      "name_ta": "பட்டுக்கோட்டை",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.4232,
      "lng": 79.32
    },
    {
      "id": "tn-madurai-melur",
      "name": "Melur",
      "name_ta": "மேலூர்",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 10.0313,
      "lng": 78.3382
    },
    {
      "id": "tn-madurai-alanganallur",
      "name": "Alanganallur",
      "name_ta": "அலங்காநல்லூர்",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 10.0474,
      "lng": 78.0904
    },
    {
      "id": "tn-madurai-vadipatti",
      "name": "Vadipatti",
      "name_ta": "வாடிப்பட்டி",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 10.0843,
      "lng": 77.961
    },
    {
      "id": "tn-madurai-thirumangalam",
      "name": "Thirumangalam",
      "name_ta": "திருமங்கலம்",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 9.8216,
      "lng": 77.9891
    },
    {
      "id": "tn-madurai-sholavandan",
      "name": "Sholavandan",
      "name_ta": "சோழவந்தான்",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 10.0221,
      "lng": 77.9615
    },
    {
      "id": "tn-madurai-kalligudi",
      "name": "Kalligudi",
      "name_ta": "கள்ளிக்குடி",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 9.7154,
      "lng": 77.9567
    },
    {
      "id": "tn-coimbatore-pollachi",
      "name": "Pollachi",
      "name_ta": "பொள்ளாச்சி",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 10.6609,
      "lng": 77.0048
    },
    {
      "id": "tn-coimbatore-mettupalayam",
      "name": "Mettupalayam",
      "name_ta": "மேட்டுப்பாளையம்",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 11.3028,
      "lng": 76.9383
    },
    {
      "id": "tn-coimbatore-sulur",
      "name": "Sulur",
      "name_ta": "சூலூர்",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 11.0254,
      "lng": 77.1246
    },
    {
      "id": "tn-coimbatore-annur",
      "name": "Annur",
      "name_ta": "அன்னூர்",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 11.2321,
      "lng": 77.1067
    },
    {
      "id": "tn-coimbatore-kinathukadavu",
      "name": "Kinathukadavu",
      "name_ta": "கிணத்துக்கடவு",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 10.8172,
      "lng": 77.0186
    },
    {
      "id": "tn-coimbatore-madukkarai",
      "name": "Madukkarai",
      "name_ta": "மதுக்கரை",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 10.9145,
      "lng": 76.9486
    },
    {
      "id": "ap-guntur-guntur",
      "name": "Guntur",
      "name_ta": "குண்டூர்",
      "district": "Guntur",
      "state": "Andhra Pradesh",
      "lat": 16.3067,
      "lng": 80.4365
    },
    {
      "id": "ka-mandya-mandya",
      "name": "Mandya",
      "name_ta": "மந்தியா",
      "district": "Mandya",
      "state": "Karnataka",
      "lat": 12.5218,
      "lng": 76.8951
    },
    {
      "id": "pb-ludhiana-ludhiana",
      "name": "Ludhiana",
      "name_ta": "லூதியானா",
      "district": "Ludhiana",
      "state": "Punjab",
      "lat": 30.901,
      "lng": 75.8573
    }
  ]
} as unknown as { source: string; panchayats: Panchayat[] };
export const panchayats: Panchayat[] = panchayatsDoc.panchayats;
export const crops = [
  {
    "id": "paddy",
    "name_en": "Paddy (Rice)",
    "name_ta": "நெல்",
    "stages": [
      {
        "id": "nursery",
        "name_en": "Nursery",
        "name_ta": "நாற்றங்கால்"
      },
      {
        "id": "transplanting",
        "name_en": "Transplanting",
        "name_ta": "நடவு"
      },
      {
        "id": "tillering",
        "name_en": "Tillering",
        "name_ta": "கத்தரிப்பு"
      },
      {
        "id": "flowering",
        "name_en": "Flowering",
        "name_ta": "பூக்கும்"
      },
      {
        "id": "harvest",
        "name_en": "Harvest",
        "name_ta": "அறுவடை"
      }
    ],
    "rules": [
      {
        "id": "spray-rain-washoff",
        "when": {
          "precip_mm_next24h_gte": 5
        },
        "action_en": "Skip pesticide/fertilizer spraying - rain expected within 24h will wash it off.",
        "action_ta": "மருந்து/உரம் தெளிக்காதீர்கள் - 24 மணி நேரத்தில் மழை வரும், கழுவிச் செல்லும்.",
        "severity": "high"
      },
      {
        "id": "spray-wind",
        "when": {
          "wind_kmh_gte": 20
        },
        "action_en": "Wind too strong for spraying - drift will waste chemical and hit neighbouring fields.",
        "action_ta": "காற்று அதிகம் - தெளிப்பு வீணாகும், அடுத்த வயலுக்குச் செல்லும்.",
        "severity": "medium"
      },
      {
        "id": "irrigate-dry-flowering",
        "when": {
          "dry_days_gte": 3,
          "stage_in": [
            "tillering",
            "flowering"
          ]
        },
        "action_en": "No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
        "action_ta": "3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்.",
        "severity": "high"
      },
      {
        "id": "drain-excess",
        "when": {
          "precip_mm_next72h_gte": 60
        },
        "action_en": "Heavy rain expected in 3 days - open field drains now to avoid waterlogging.",
        "action_ta": "3 நாட்களில் கனமழை - வயல் வடிகால்களை இப்போதே திறக்கவும்.",
        "severity": "high"
      },
      {
        "id": "harvest-window",
        "when": {
          "stage_in": [
            "harvest"
          ],
          "precip_mm_next48h_gte": 10
        },
        "action_en": "Rain in the next 2 days - harvest mature crop today if 80% grains are golden.",
        "action_ta": "2 நாட்களில் மழை - 80% மணி மஞ்சளாகி இருந்தால் இன்றே அறுவடை செய்யுங்கள்.",
        "severity": "high"
      },
      {
        "id": "blast-humidity",
        "when": {
          "humidity_pct_gte": 85,
          "temp_c_between": [
            22,
            28
          ]
        },
        "action_en": "Humid, mild weather favours blast disease - inspect leaf tips this week.",
        "action_ta": "ஈரப்பதமான வானிலை பிளாஸ்ட் நோய்க்கு ஏற்றது - இலை நுனிகளை ஆராயுங்கள்.",
        "severity": "medium"
      }
    ]
  },
  {
    "id": "banana",
    "name_en": "Banana",
    "name_ta": "வாழை",
    "stages": [
      {
        "id": "planting",
        "name_en": "Planting",
        "name_ta": "நடவு"
      },
      {
        "id": "vegetative",
        "name_en": "Vegetative",
        "name_ta": "வளர்ச்சி"
      },
      {
        "id": "bunching",
        "name_en": "Bunch emergence",
        "name_ta": "குலை தோன்றல்"
      },
      {
        "id": "harvest",
        "name_en": "Harvest",
        "name_ta": "அறுவடை"
      }
    ],
    "rules": [
      {
        "id": "wind-propping",
        "when": {
          "wind_kmh_gte": 30
        },
        "action_en": "Strong winds expected - prop tall plants with casuarina poles today.",
        "action_ta": "பலத்த காற்று - உயரமான தாவரங்களுக்கு இன்றே சவுக்கு கம்பு தாங்கவும்.",
        "severity": "high"
      },
      {
        "id": "irrigate-dry-bunching",
        "when": {
          "dry_days_gte": 4,
          "stage_in": [
            "bunching"
          ]
        },
        "action_en": "Dry spell during bunch emergence - irrigate; water stress now shrinks fingers.",
        "action_ta": "குலை தோன்றும் நிலையில் வறட்சி - நீர்ப்பாய்ச்சல் செய்யுங்கள், இல்லையெனில் விரல்கள் சிறிதாகும்.",
        "severity": "high"
      },
      {
        "id": "spray-rain-washoff",
        "when": {
          "precip_mm_next24h_gte": 5
        },
        "action_en": "Skip spraying - rain within 24h will wash it off.",
        "action_ta": "தெளிப்பைத் தவிர்க்கவும் - 24 மணி நேரத்தில் மழை கழுவிச் செல்லும்.",
        "severity": "high"
      }
    ]
  },
  {
    "id": "groundnut",
    "name_en": "Groundnut",
    "name_ta": "நிலக்கடலை",
    "stages": [
      {
        "id": "sowing",
        "name_en": "Sowing",
        "name_ta": "விதைப்பு"
      },
      {
        "id": "flowering",
        "name_en": "Flowering",
        "name_ta": "பூக்கும்"
      },
      {
        "id": "pegging",
        "name_en": "Pegging",
        "name_ta": "கடலை உருவாக்கம்"
      },
      {
        "id": "harvest",
        "name_en": "Harvest",
        "name_ta": "அறுவடை"
      }
    ],
    "rules": [
      {
        "id": "sowing-rain-window",
        "when": {
          "stage_in": [
            "sowing"
          ],
          "precip_mm_next72h_gte": 15
        },
        "action_en": "Good sowing window - 15mm+ rain expected in 3 days. Finish sowing before it.",
        "action_ta": "விதைக்க நல்ல நேரம் - 3 நாட்களில் 15மிமீ+ மழை. அதற்குள் விதைத்து முடிக்கவும்.",
        "severity": "info"
      },
      {
        "id": "pegging-dry",
        "when": {
          "dry_days_gte": 5,
          "stage_in": [
            "pegging"
          ]
        },
        "action_en": "Pegging needs soil moisture - give a light irrigation.",
        "action_ta": "கடலை உருவாக்கத்திற்கு ஈரம் வேண்டும் - லேசாக நீர்ப்பாய்ச்சல் செய்யுங்கள்.",
        "severity": "medium"
      },
      {
        "id": "harvest-rain",
        "when": {
          "stage_in": [
            "harvest"
          ],
          "precip_mm_next48h_gte": 10
        },
        "action_en": "Rain in 2 days - pull mature pods before the field gets wet.",
        "action_ta": "2 நாட்களில் மழை - வயல் ஈரமாகும் முன் முதிர்ந்த கடலையைப் பிடுங்கவும்.",
        "severity": "high"
      }
    ]
  },
  {
    "id": "cotton",
    "name_en": "Cotton",
    "name_ta": "பருத்தி",
    "stages": [
      {
        "id": "sowing",
        "name_en": "Sowing",
        "name_ta": "விதைப்பு"
      },
      {
        "id": "vegetative",
        "name_en": "Vegetative",
        "name_ta": "வளர்ச்சி"
      },
      {
        "id": "boll",
        "name_en": "Boll formation",
        "name_ta": "காய் உருவாக்கம்"
      },
      {
        "id": "picking",
        "name_en": "Picking",
        "name_ta": "பறித்தல்"
      }
    ],
    "rules": [
      {
        "id": "pink-bollworm-humid",
        "when": {
          "humidity_pct_gte": 80,
          "stage_in": [
            "boll"
          ]
        },
        "action_en": "Humid weather during boll stage - set pheromone traps and scout for pink bollworm.",
        "action_ta": "காய் நிலையில் ஈரப்பத வானிலை - ஃபெரோமோன் பொறிகள் வைத்து இளம் புழுவைக் கண்காணிக்கவும்.",
        "severity": "medium"
      },
      {
        "id": "picking-rain",
        "when": {
          "stage_in": [
            "picking"
          ],
          "precip_mm_next48h_gte": 5
        },
        "action_en": "Rain in 2 days stains open bolls - pick opened cotton today.",
        "action_ta": "2 நாட்களில் மழை திறந்த காய்களைக் கறைப்படுத்தும் - இன்றே பருத்தி பறிக்கவும்.",
        "severity": "high"
      },
      {
        "id": "spray-rain-washoff",
        "when": {
          "precip_mm_next24h_gte": 5
        },
        "action_en": "Skip spraying - rain within 24h will wash it off.",
        "action_ta": "தெளிப்பைத் தவிர்க்கவும் - 24 மணி நேரத்தில் மழை கழுவிச் செல்லும்.",
        "severity": "high"
      }
    ]
  }
] as unknown as Crop[];
export const fallbacks: Record<string, Advisory> = {
  "ap-guntur-guntur__paddy__transplanting": {
    "panchayat": {
      "id": "ap-guntur-guntur",
      "name": "Guntur",
      "name_ta": "குண்டூர்",
      "district": "Guntur",
      "state": "Andhra Pradesh",
      "lat": 16.3067,
      "lng": 80.4365
    },
    "crop": "paddy",
    "stage": "transplanting",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:40.449Z",
    "generatedBy": "rules",
    "summaryEn": "Guntur: Paddy (Rice) at Transplanting stage. Rain expected today (7.1 mm). High 32.5°C, low 24.9°C. Priority: Skip pesticide/fertilizer spraying - rain expected within 24h will wash it off.",
    "summaryTa": "குண்டூர்: நெல் நடவு நிலையில். இன்று மழை எதிர்பார்க்கப்படுகிறது (7.1 மிமீ). அதிகபட்சம் 32.5°செ, குறைந்தபட்சம் 24.9°செ. முக்கியம்: மருந்து/உரம் தெளிக்காதீர்கள் - 24 மணி நேரத்தில் மழை வரும், கழுவிச் செல்லும்.",
    "actions": [
      {
        "ruleId": "spray-rain-washoff",
        "severity": "high",
        "en": "Skip pesticide/fertilizer spraying - rain expected within 24h will wash it off.",
        "ta": "மருந்து/உரம் தெளிக்காதீர்கள் - 24 மணி நேரத்தில் மழை வரும், கழுவிச் செல்லும்."
      },
      {
        "ruleId": "spray-wind",
        "severity": "medium",
        "en": "Wind too strong for spraying - drift will waste chemical and hit neighbouring fields.",
        "ta": "காற்று அதிகம் - தெளிப்பு வீணாகும், அடுத்த வயலுக்குச் செல்லும்."
      }
    ],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 24.9,
        "tmax": 32.5,
        "precipMm": 7.1,
        "precipProbMax": 100,
        "humidityAvg": 70,
        "windMaxKmh": 22,
        "confidence": "medium"
      },
      {
        "date": "2026-09-26",
        "tmin": 26.3,
        "tmax": 32.9,
        "precipMm": 0,
        "precipProbMax": 2,
        "humidityAvg": 69,
        "windMaxKmh": 17,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 25.3,
        "tmax": 33.1,
        "precipMm": 0,
        "precipProbMax": 6,
        "humidityAvg": 74,
        "windMaxKmh": 15,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 23.7,
        "tmax": 33.1,
        "precipMm": 0,
        "precipProbMax": 2,
        "humidityAvg": 77,
        "windMaxKmh": 12,
        "confidence": "high"
      },
      {
        "date": "2026-09-29",
        "tmin": 24.5,
        "tmax": 33.2,
        "precipMm": 0,
        "precipProbMax": 8,
        "humidityAvg": 77,
        "windMaxKmh": 11,
        "confidence": "high"
      }
    ]
  },
  "ka-mandya-mandya__paddy__tillering": {
    "panchayat": {
      "id": "ka-mandya-mandya",
      "name": "Mandya",
      "name_ta": "மந்தியா",
      "district": "Mandya",
      "state": "Karnataka",
      "lat": 12.5218,
      "lng": 76.8951
    },
    "crop": "paddy",
    "stage": "tillering",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:41.021Z",
    "generatedBy": "rules",
    "summaryEn": "Mandya: Paddy (Rice) at Tillering stage. Rain expected today (6.3 mm). High 28.5°C, low 21.7°C. Priority: Skip pesticide/fertilizer spraying - rain expected within 24h will wash it off.",
    "summaryTa": "மந்தியா: நெல் கத்தரிப்பு நிலையில். இன்று மழை எதிர்பார்க்கப்படுகிறது (6.3 மிமீ). அதிகபட்சம் 28.5°செ, குறைந்தபட்சம் 21.7°செ. முக்கியம்: மருந்து/உரம் தெளிக்காதீர்கள் - 24 மணி நேரத்தில் மழை வரும், கழுவிச் செல்லும்.",
    "actions": [
      {
        "ruleId": "spray-rain-washoff",
        "severity": "high",
        "en": "Skip pesticide/fertilizer spraying - rain expected within 24h will wash it off.",
        "ta": "மருந்து/உரம் தெளிக்காதீர்கள் - 24 மணி நேரத்தில் மழை வரும், கழுவிச் செல்லும்."
      },
      {
        "ruleId": "spray-wind",
        "severity": "medium",
        "en": "Wind too strong for spraying - drift will waste chemical and hit neighbouring fields.",
        "ta": "காற்று அதிகம் - தெளிப்பு வீணாகும், அடுத்த வயலுக்குச் செல்லும்."
      }
    ],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 21.7,
        "tmax": 28.5,
        "precipMm": 6.3,
        "precipProbMax": 100,
        "humidityAvg": 78,
        "windMaxKmh": 22,
        "confidence": "medium"
      },
      {
        "date": "2026-09-26",
        "tmin": 19.8,
        "tmax": 30.3,
        "precipMm": 0.5,
        "precipProbMax": 46,
        "humidityAvg": 71,
        "windMaxKmh": 19,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 18.9,
        "tmax": 30.5,
        "precipMm": 0,
        "precipProbMax": 21,
        "humidityAvg": 73,
        "windMaxKmh": 14,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 20.7,
        "tmax": 31.1,
        "precipMm": 14.6,
        "precipProbMax": 84,
        "humidityAvg": 81,
        "windMaxKmh": 12,
        "confidence": "low"
      },
      {
        "date": "2026-09-29",
        "tmin": 20.7,
        "tmax": 30.3,
        "precipMm": 6.9,
        "precipProbMax": 88,
        "humidityAvg": 86,
        "windMaxKmh": 12,
        "confidence": "high"
      }
    ]
  },
  "tn-coimbatore-pollachi__banana__vegetative": {
    "panchayat": {
      "id": "tn-coimbatore-pollachi",
      "name": "Pollachi",
      "name_ta": "பொள்ளாச்சி",
      "district": "Coimbatore",
      "state": "Tamil Nadu",
      "lat": 10.6609,
      "lng": 77.0048
    },
    "crop": "banana",
    "stage": "vegetative",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:39.875Z",
    "generatedBy": "rules",
    "summaryEn": "Pollachi: Banana at Vegetative stage. Light rain possible today (1.9 mm). High 32.2°C, low 23.9°C. Priority: Strong winds expected - prop tall plants with casuarina poles today.",
    "summaryTa": "பொள்ளாச்சி: வாழை வளர்ச்சி நிலையில். இன்று லேசான மழை சாத்தியம் (1.9 மிமீ). அதிகபட்சம் 32.2°செ, குறைந்தபட்சம் 23.9°செ. முக்கியம்: பலத்த காற்று - உயரமான தாவரங்களுக்கு இன்றே சவுக்கு கம்பு தாங்கவும்.",
    "actions": [
      {
        "ruleId": "wind-propping",
        "severity": "high",
        "en": "Strong winds expected - prop tall plants with casuarina poles today.",
        "ta": "பலத்த காற்று - உயரமான தாவரங்களுக்கு இன்றே சவுக்கு கம்பு தாங்கவும்."
      }
    ],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 23.9,
        "tmax": 32.2,
        "precipMm": 1.9,
        "precipProbMax": 54,
        "humidityAvg": 69,
        "windMaxKmh": 31,
        "confidence": "high"
      },
      {
        "date": "2026-09-26",
        "tmin": 24.7,
        "tmax": 31.6,
        "precipMm": 0.4,
        "precipProbMax": 24,
        "humidityAvg": 68,
        "windMaxKmh": 30,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 23.6,
        "tmax": 33.3,
        "precipMm": 0.4,
        "precipProbMax": 31,
        "humidityAvg": 69,
        "windMaxKmh": 25,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 23.9,
        "tmax": 34.4,
        "precipMm": 0.7,
        "precipProbMax": 58,
        "humidityAvg": 68,
        "windMaxKmh": 23,
        "confidence": "high"
      },
      {
        "date": "2026-09-29",
        "tmin": 24.1,
        "tmax": 33.4,
        "precipMm": 1.2,
        "precipProbMax": 65,
        "humidityAvg": 70,
        "windMaxKmh": 22,
        "confidence": "high"
      }
    ]
  },
  "tn-madurai-melur__groundnut__pegging": {
    "panchayat": {
      "id": "tn-madurai-melur",
      "name": "Melur",
      "name_ta": "மேலூர்",
      "district": "Madurai",
      "state": "Tamil Nadu",
      "lat": 10.0313,
      "lng": 78.3382
    },
    "crop": "groundnut",
    "stage": "pegging",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:39.309Z",
    "generatedBy": "rules",
    "summaryEn": "Melur: Groundnut at Pegging stage. No rain expected today. High 34.6°C, low 26.6°C. Conditions look normal - follow your regular schedule.",
    "summaryTa": "மேலூர்: நிலக்கடலை கடலை உருவாக்கம் நிலையில். இன்று மழை எதிர்பார்க்கப்படவில்லை. அதிகபட்சம் 34.6°செ, குறைந்தபட்சம் 26.6°செ. நிலை சாதாரணம் - வழக்கமான பணிகளைத் தொடரவும்.",
    "actions": [],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 26.6,
        "tmax": 34.6,
        "precipMm": 0,
        "precipProbMax": 0,
        "humidityAvg": 53,
        "windMaxKmh": 23,
        "confidence": "high"
      },
      {
        "date": "2026-09-26",
        "tmin": 24.7,
        "tmax": 34.7,
        "precipMm": 0.3,
        "precipProbMax": 8,
        "humidityAvg": 62,
        "windMaxKmh": 9,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 25.1,
        "tmax": 35.1,
        "precipMm": 0.3,
        "precipProbMax": 47,
        "humidityAvg": 64,
        "windMaxKmh": 15,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 26.2,
        "tmax": 35.6,
        "precipMm": 8.3,
        "precipProbMax": 86,
        "humidityAvg": 74,
        "windMaxKmh": 10,
        "confidence": "medium"
      },
      {
        "date": "2026-09-29",
        "tmin": 25.2,
        "tmax": 32.5,
        "precipMm": 4.9,
        "precipProbMax": 76,
        "humidityAvg": 79,
        "windMaxKmh": 11,
        "confidence": "high"
      }
    ]
  },
  "tn-thanjavur-kumbakonam__banana__bunching": {
    "panchayat": {
      "id": "tn-thanjavur-kumbakonam",
      "name": "Kumbakonam",
      "name_ta": "கும்பகோணம்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.9602,
      "lng": 79.3845
    },
    "crop": "banana",
    "stage": "bunching",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:38.736Z",
    "generatedBy": "rules",
    "summaryEn": "Kumbakonam: Banana at Bunch emergence stage. No rain expected today. High 32.9°C, low 27.5°C. Conditions look normal - follow your regular schedule.",
    "summaryTa": "கும்பகோணம்: வாழை குலை தோன்றல் நிலையில். இன்று மழை எதிர்பார்க்கப்படவில்லை. அதிகபட்சம் 32.9°செ, குறைந்தபட்சம் 27.5°செ. நிலை சாதாரணம் - வழக்கமான பணிகளைத் தொடரவும்.",
    "actions": [],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 27.5,
        "tmax": 32.9,
        "precipMm": 0,
        "precipProbMax": 7,
        "humidityAvg": 59,
        "windMaxKmh": 23,
        "confidence": "high"
      },
      {
        "date": "2026-09-26",
        "tmin": 25.9,
        "tmax": 35,
        "precipMm": 0,
        "precipProbMax": 3,
        "humidityAvg": 64,
        "windMaxKmh": 19,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 26.4,
        "tmax": 35.4,
        "precipMm": 0.1,
        "precipProbMax": 30,
        "humidityAvg": 65,
        "windMaxKmh": 14,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 25.9,
        "tmax": 34.8,
        "precipMm": 8.4,
        "precipProbMax": 72,
        "humidityAvg": 78,
        "windMaxKmh": 12,
        "confidence": "medium"
      },
      {
        "date": "2026-09-29",
        "tmin": 24.2,
        "tmax": 33.8,
        "precipMm": 4.2,
        "precipProbMax": 55,
        "humidityAvg": 83,
        "windMaxKmh": 11,
        "confidence": "high"
      }
    ]
  },
  "tn-thanjavur-orathanadu__paddy__flowering": {
    "panchayat": {
      "id": "tn-thanjavur-orathanadu",
      "name": "Orathanadu",
      "name_ta": "ஓரத்தநாடு",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.6277,
      "lng": 79.2525
    },
    "crop": "paddy",
    "stage": "flowering",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:37.607Z",
    "generatedBy": "rules",
    "summaryEn": "Orathanadu: Paddy (Rice) at Flowering stage. No rain expected today. High 33.4°C, low 26.5°C. Priority: No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
    "summaryTa": "ஓரத்தநாடு: நெல் பூக்கும் நிலையில். இன்று மழை எதிர்பார்க்கப்படவில்லை. அதிகபட்சம் 33.4°செ, குறைந்தபட்சம் 26.5°செ. முக்கியம்: 3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்.",
    "actions": [
      {
        "ruleId": "irrigate-dry-flowering",
        "severity": "high",
        "en": "No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
        "ta": "3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்."
      }
    ],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 26.5,
        "tmax": 33.4,
        "precipMm": 0,
        "precipProbMax": 4,
        "humidityAvg": 61,
        "windMaxKmh": 15,
        "confidence": "high"
      },
      {
        "date": "2026-09-26",
        "tmin": 25.6,
        "tmax": 35.4,
        "precipMm": 0.1,
        "precipProbMax": 7,
        "humidityAvg": 65,
        "windMaxKmh": 20,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 26.4,
        "tmax": 34.8,
        "precipMm": 0.2,
        "precipProbMax": 15,
        "humidityAvg": 68,
        "windMaxKmh": 15,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 26.6,
        "tmax": 34.6,
        "precipMm": 0.8,
        "precipProbMax": 66,
        "humidityAvg": 76,
        "windMaxKmh": 14,
        "confidence": "high"
      },
      {
        "date": "2026-09-29",
        "tmin": 25.1,
        "tmax": 34.3,
        "precipMm": 2,
        "precipProbMax": 65,
        "humidityAvg": 78,
        "windMaxKmh": 11,
        "confidence": "high"
      }
    ]
  },
  "tn-thanjavur-orathanadu__paddy__tillering": {
    "panchayat": {
      "id": "tn-thanjavur-orathanadu",
      "name": "Orathanadu",
      "name_ta": "ஓரத்தநாடு",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.6277,
      "lng": 79.2525
    },
    "crop": "paddy",
    "stage": "tillering",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:37.043Z",
    "generatedBy": "rules",
    "summaryEn": "Orathanadu: Paddy (Rice) at Tillering stage. No rain expected today. High 33.4°C, low 26.5°C. Priority: No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
    "summaryTa": "ஓரத்தநாடு: நெல் கத்தரிப்பு நிலையில். இன்று மழை எதிர்பார்க்கப்படவில்லை. அதிகபட்சம் 33.4°செ, குறைந்தபட்சம் 26.5°செ. முக்கியம்: 3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்.",
    "actions": [
      {
        "ruleId": "irrigate-dry-flowering",
        "severity": "high",
        "en": "No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
        "ta": "3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்."
      }
    ],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 26.5,
        "tmax": 33.4,
        "precipMm": 0,
        "precipProbMax": 4,
        "humidityAvg": 61,
        "windMaxKmh": 15,
        "confidence": "high"
      },
      {
        "date": "2026-09-26",
        "tmin": 25.6,
        "tmax": 35.4,
        "precipMm": 0.1,
        "precipProbMax": 7,
        "humidityAvg": 65,
        "windMaxKmh": 20,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 26.4,
        "tmax": 34.8,
        "precipMm": 0.2,
        "precipProbMax": 15,
        "humidityAvg": 68,
        "windMaxKmh": 15,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 26.6,
        "tmax": 34.6,
        "precipMm": 0.8,
        "precipProbMax": 66,
        "humidityAvg": 76,
        "windMaxKmh": 14,
        "confidence": "high"
      },
      {
        "date": "2026-09-29",
        "tmin": 25.1,
        "tmax": 34.3,
        "precipMm": 2,
        "precipProbMax": 65,
        "humidityAvg": 78,
        "windMaxKmh": 11,
        "confidence": "high"
      }
    ]
  },
  "tn-thanjavur-papanasam__paddy__tillering": {
    "panchayat": {
      "id": "tn-thanjavur-papanasam",
      "name": "Papanasam",
      "name_ta": "பாபநாசம்",
      "district": "Thanjavur",
      "state": "Tamil Nadu",
      "lat": 10.9296,
      "lng": 79.2705
    },
    "crop": "paddy",
    "stage": "tillering",
    "lang": "ta",
    "generatedAt": "2026-09-25T17:10:38.172Z",
    "generatedBy": "rules",
    "summaryEn": "Papanasam: Paddy (Rice) at Tillering stage. No rain expected today. High 32.7°C, low 27.7°C. Priority: No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
    "summaryTa": "பாபநாசம்: நெல் கத்தரிப்பு நிலையில். இன்று மழை எதிர்பார்க்கப்படவில்லை. அதிகபட்சம் 32.7°செ, குறைந்தபட்சம் 27.7°செ. முக்கியம்: 3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்.",
    "actions": [
      {
        "ruleId": "irrigate-dry-flowering",
        "severity": "high",
        "en": "No rain for 3+ days during a critical stage - irrigate today, preferably evening.",
        "ta": "3+ நாட்கள் மழை இல்லை, முக்கிய நிலை - இன்று மாலை நீர்ப்பாய்ச்சல் செய்யுங்கள்."
      },
      {
        "ruleId": "spray-wind",
        "severity": "medium",
        "en": "Wind too strong for spraying - drift will waste chemical and hit neighbouring fields.",
        "ta": "காற்று அதிகம் - தெளிப்பு வீணாகும், அடுத்த வயலுக்குச் செல்லும்."
      }
    ],
    "forecastDays": [
      {
        "date": "2026-09-25",
        "tmin": 27.7,
        "tmax": 32.7,
        "precipMm": 0,
        "precipProbMax": 11,
        "humidityAvg": 57,
        "windMaxKmh": 24,
        "confidence": "high"
      },
      {
        "date": "2026-09-26",
        "tmin": 26,
        "tmax": 35.2,
        "precipMm": 0,
        "precipProbMax": 4,
        "humidityAvg": 63,
        "windMaxKmh": 21,
        "confidence": "high"
      },
      {
        "date": "2026-09-27",
        "tmin": 26.6,
        "tmax": 35.3,
        "precipMm": 0.2,
        "precipProbMax": 34,
        "humidityAvg": 64,
        "windMaxKmh": 14,
        "confidence": "high"
      },
      {
        "date": "2026-09-28",
        "tmin": 25.9,
        "tmax": 34.9,
        "precipMm": 7.3,
        "precipProbMax": 68,
        "humidityAvg": 76,
        "windMaxKmh": 12,
        "confidence": "medium"
      },
      {
        "date": "2026-09-29",
        "tmin": 24.2,
        "tmax": 34.1,
        "precipMm": 4.1,
        "precipProbMax": 58,
        "humidityAvg": 81,
        "windMaxKmh": 9,
        "confidence": "high"
      }
    ]
  }
} as unknown as Record<string, Advisory>;
